## Setup

In [1]:
import os

from numpy import ndarray
from sklearn.gaussian_process.kernels import Matern, RationalQuadratic
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats._qmc import Sobol
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
from scipy.stats import norm
from scipy.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

# A nod to Hitchhikers guide to the Galaxy
random_seed=42
np.random.seed(random_seed)

#UCB -  Kappa
# 0.1-1 Exploitation
# 2-5 Balance
# 5-10 Exploratory
KAPPA_BALANCED = 5
KAPPA_EXPLOIT = 0.1
KAPPA_EXPLORE = 10
KAPPA_EXTREME_EXPLORE = 20

KAPPAS = [KAPPA_EXPLOIT, KAPPA_BALANCED, KAPPA_EXPLORE,KAPPA_EXTREME_EXPLORE]


#EI
#0 - Exploitation
#0.01-0.1 - Small Explore
#0.1-0.5 - Moderate Explore
# 0.5+ - Higher explore
XI_EXPLOIT=0
XI_SMALL = 0.1
XI_MODERATE = 0.5
XI_HIGH=20


XIS = [XI_EXPLOIT,XI_SMALL, XI_MODERATE, XI_HIGH]

ACQUISTION_EI = 'ei'
ACQUISTION_UCB = 'ucb'


def penaltyWeightAndScaleForDimension(d):
    #Curse of dimensionality means this needs to be much tighter at higher dimensions
    #This is intended to reduce the acquisition function's information gain by 10% if the point has a Euclidean distance of 1/20th or 1/50th of a boundary.
    if d <= 5:
        return 0.1, 0.05
    else:
        return 0.1, 0.02




In [2]:
def upper_confidence_bound(mu, sigma, kappa):
    """
    Upper Confidence Bound (UCB) acquisition function.
    
    UCB = mean + kappa * std
    
    Parameters:
    -----------
    mu : predicted mean
    sigma : predicted standard deviation
    kappa : exploration parameter (higher = more exploration)
    """
    return mu + kappa * sigma

#
def expected_improvement(mu, sigma, y_best, xi):
    """
    Expected Improvement (EI) acquisition function.
    
    EI = E[max(f(x) - f(x_best), 0)]
    
    Parameters:
    -----------
    mu : predicted mean
    sigma : predicted standard deviation  
    y_best : best observed value so far
    xi : exploration parameter
    """
    # To avoid division by zero, clamp sigma to a very small non-zero - we also add exit clause later for same value.
    sigma = np.maximum(sigma, 1e-16)

    with np.errstate(divide='warn'):
        improvement = mu - y_best - xi
        Z = improvement / sigma
        ei = improvement * norm.cdf(Z) + sigma * norm.pdf(Z)
        ei[sigma == 1e-16] = 0.0
    return ei


In [3]:

def fmt(v):
        return float(f"{v:.8f}")


def summary_stats(x):
    return {
        "min": fmt(np.min(x)),
        "max": fmt(np.max(x)),
        "mean": fmt(np.mean(x)),
        "std": fmt(np.std(x)),
        "q1": fmt(np.percentile(x, 25)),
        "median": fmt(np.percentile(x, 50)),
        "q3": fmt(np.percentile(x, 75)),
    }


from sklearn.model_selection import GridSearchCV
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF

def findTunedGaussianProcessRegressor(X_samples, y_samples):
    #Use grid search to work out which GP hyper params are best to fit to this problem
    param_grid = {
        'kernel': [RBF(length_scale=0.5), RBF(length_scale=1.0), RBF(length_scale=2.0),
                   Matern(nu=0.5, length_scale=1.0), Matern(nu=1.5,length_scale=1.0 ), Matern(nu=2.5, length_scale=1.0),
                   Matern(nu=0.5, length_scale=2.0), Matern(nu=1.5,length_scale=2.0 ), Matern(nu=2.5, length_scale=2.0),
                   RationalQuadratic(alpha=1.0, length_scale=1.0), RationalQuadratic(alpha=1.0, length_scale=2.0)],
        'alpha': [1e-8, 1e-6, 1e-4, 1e-2],
        'n_restarts_optimizer': [5, 10, 20]
    }
    gp = GaussianProcessRegressor()
    grid_search = GridSearchCV(gp, param_grid, cv=3)
    grid_search.fit(X_samples, y_samples)

    return grid_search.best_estimator_, grid_search.best_params_



def bayesian_optimization_next_point(
        n_dims,
        X_samples,
        y_samples,
        acquisition,
        kappa = KAPPA_BALANCED,
        xi = XI_SMALL,
        n_sobol=None,
        n_local=None,
        gp=None):

    """
    Bayesian Optimization acquisition optimizer - after research about search spaces.
    Parameters
    ----------
    n_dims : int
        Number of dimensions
    X_samples : array (N, D)
        Existing sample inputs
    y_samples : array (N,)
        Existing sample outputs
    acquisition : str
        'ei' or 'ucb'
    n_sobol : int
        Number of Sobol candidate points
    n_local : int
        Number of local optimizations
    kappa: int
        Exploration parameter (higher = more exploration)
    gp: GaussianProcessor
        Gaussian Processor to use on fitting≥
    """

    if n_sobol is None:
        n_sobol = 16384 * n_dims
    if n_local is None:
        n_local = 32 * n_dims

    bounds = [(0.0, 1.0) for _ in range(n_dims)]
    penaltyWeight, penalityScale = penaltyWeightAndScaleForDimension(n_dims)

    if acquisition == ACQUISTION_EI:
        print(f"Using Expected Improvement Acquisition function with xi = {xi}")
    else:
        print(f"Using UCB Acquisition function with Kappa = {kappa}")


    # -----------------------------
    # 1. Fit Gaussian Process
    #
    #  alpha is the noise level
    #  n_restarts_optimizer is a hyper-parameter
    #  normalize_y improves stability
    # -----------------------------
    if gp is None:
        kernel = ConstantKernel(1.0) * Matern(nu=2.5)
        gp = GaussianProcessRegressor(
            kernel=kernel,
            alpha=1e-6,
            n_restarts_optimizer=10,
            normalize_y=True
        )

    gp.fit(X_samples, y_samples)


    # -----------------------------
    # 2. Acquisition function
    # -----------------------------

    # -----------------------------
    # 2.1 Boundary Penalty.
    # GP tends to hug the boundary, so add a penalty if a suggested point is close to boundary.
    # Scale controls how far from the boundary the penalty reaches. At scale=0.05, a point at x=0.05 gets a penalty of exp(-1) ≈ 0.37, meaning the penalty is significant only within the last ~5% of the search space.
    # Weight controls how strongly that penalty suppresses the acquisition value. At weight=0.1, the maximum possible suppression is 10% of the acquisition value.
    #
    # -----------------------------
    def boundary_penalty(X, weight=0.1, scale=0.05):
        X = np.atleast_2d(X)
        d = np.minimum(X, 1.0 - X)    #Find point closest to boundary at 0 or 1 in any dimension.
        penalty = np.mean(np.exp(-d / scale), axis=1)   #exp(-small) tends towards 1, exp(-large) tends towards 0. Mean takes into account other dimensions.
        return weight * penalty


    def acq(X):
        X = np.atleast_2d(X)
        mu, sigma = gp.predict(X, return_std=True)

        if acquisition == ACQUISTION_EI:
            val = expected_improvement(mu, sigma, y_samples.max(), xi)
        else:
            val = upper_confidence_bound(mu, sigma, kappa)

        penalty = boundary_penalty(X, weight=penaltyWeight, scale=penalityScale)
        return val * (1 - penalty)


    # -----------------------------
    # 3. Sobol global search
    #
    # Provides a better search than random of the space, but we then run a vectorized evaluation loop and pick the top results to focus optimizing
    # i.e. maximising in local optimization (actually we minimise the -value)
    # -----------------------------
    sobol = Sobol(d=n_dims, scramble=True, seed=random_seed*n_dims) #Stop the same points for each function.

    X_candidates = sobol.random(n_sobol)
    acq_vals = acq(X_candidates)

    # Filter out duplicate candidates - because acquisition functions can suggest previous points.
    def is_duplicate(x, X_samples, tol=1e-5):
        return np.any(np.linalg.norm(X_samples - x, axis=1) < tol)
    mask = np.array([not is_duplicate(x, X_samples) for x in X_candidates])
    X_candidates = X_candidates[mask]
    acq_vals = acq_vals[mask]


    # Pick best Sobol points
    best_idx = np.argsort(-acq_vals)[:n_local]
    X_start = X_candidates[best_idx]

    print(f"\t{len(X_candidates)} Sobol candidates, best {len(X_start)} to be minimised in local search")
    print(f"\tInitial acquisition function stats {summary_stats(acq_vals)}")

    # -----------------------------
    # 4. Local optimization
    # -----------------------------
    def objective(x):
        return -acq(x)  # minimize negative acquisition


    best_x = None
    best_val = -np.inf

    for i, x0 in enumerate(X_start):
        result = minimize(
            objective,
            x0,
            bounds=bounds,
            method="L-BFGS-B"
        )

        val = -result.fun
        if val > best_val:
            best_val = val
            best_x = result.x
            print(f"\tLocal search {i+1}/{n_local}, x={result.x}, val={val}, best={best_val:.10f}")

    return best_x, best_val



In [4]:
#Store Results from runs
runResults = {}
gpKernels = {}



In [5]:
def sortByLargestOutputDescending(arr):
    return  arr[np.argsort(arr[:, 2])[::-1]]

def formatOutputForSubmission( nextInputToTest: ndarray):
    return np.array2string(nextInputToTest, separator='-', precision=6, floatmode='fixed').strip('[]')



def findNextGuess(functionName, f_Inputs, f_Outputs, showKnown=True):

    f_maxInput = np.max(f_Inputs, axis=0) #Output per dimension
    f_minInput = np.min(f_Inputs, axis=0)
    f_maxOutput = np.max(f_Outputs)
    f_minOutput = np.min(f_Outputs)
    numDimensions = len(f_maxInput)

    f_inputOutput = np.column_stack((f_Inputs, f_Outputs))
    f_inputOutputSorted = sortByLargestOutputDescending(f_inputOutput)

    print('********************')
    print(functionName, ' - ', numDimensions, 'D')
    print('********************')
    print(' Inputs -   Min:',  f_minInput, ', Max: ', f_maxInput )
    print(' Output -   Min:',  f_minOutput, ', Max (Best): ', f_maxOutput)


    if (showKnown):
        print()
        print(np.array2string(f_inputOutputSorted, floatmode='fixed', precision=6))
        print()

    print(f"Starting {numDimensions}D Bayes Optimisation from {len(f_Inputs)} known samples")
    print()


    #Solve the GaussianProcessor hyper parameters and record the best fit.
    gpr, bestParams = findTunedGaussianProcessRegressor(f_Inputs, f_Outputs)
    print(f"Best GP kernel and hyperparams for problem is ${bestParams}")
    gpKernels[functionName] = bestParams


    functionProposedPoints = {}
    count = -1
    # EI
    for xi in XIS:
        nextInputToTest, acqFunctionValue = bayesian_optimization_next_point(
            n_dims=numDimensions,
            X_samples=f_Inputs,
            y_samples=f_Outputs,
            acquisition=ACQUISTION_EI,
            xi=xi,
            gp=gpr
        )

        count += 1
        functionProposedPoints[count] = formatOutputForSubmission(nextInputToTest)
        print()
        print(f'\tProposed next point to try: {functionProposedPoints[count]}')
        print()

    for k in KAPPAS:
        nextInputToTest, acqFunctionValue = bayesian_optimization_next_point(
            n_dims=numDimensions,
            X_samples=f_Inputs,
            y_samples=f_Outputs,
            acquisition=ACQUISTION_UCB,
            kappa=k,
            gp=gpr
        )
        count += 1
        functionProposedPoints[count] = formatOutputForSubmission(nextInputToTest)
        print()
        print(f'\tProposed next point to try: {functionProposedPoints[count]}')
        print()

    runResults[functionName] = functionProposedPoints


In [6]:
def collatePreviousSubmissions(functionNo):
    functionIndex = functionNo -1
    assert(functionIndex >= 0)
    assert(functionIndex <= 7)

    #Search for subfolders and find last submission week and results
    week_folders = [d for d in os.listdir("submission_results") if d.startswith("week") ]
    week_folders.sort(key=lambda w: int(w.replace("week", "")))
    last_week = week_folders[-1]
    week_dir = os.path.join("submission_results", last_week)


    def load_file(file_name):
        file_path = os.path.join(week_dir, file_name)
        all_lines = []
        with open(file_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Parse the trusted Python literals
                parsedData = eval(line, {"array": np.array, "np": np})
                all_lines.append(parsedData)
        return all_lines
    allSubmissions = load_file("inputs.txt")
    allResults = load_file("outputs.txt")

    #Extract the functionNo inputs and outputs only and return those arrays only
    functionSubmissions = np.array([line[functionIndex] for line in allSubmissions])
    functionResults = np.array([line[functionIndex] for line in allResults])

    return functionSubmissions, functionResults


In [7]:
def combineInitialDataAndSubmissionsToDate(functionNo):
    assert(functionNo >= 1)
    assert(functionNo <= 8)

    initialInputs = np.load(f'initial_data/function_{functionNo}/initial_inputs.npy')
    initialOutputs = np.load(f'initial_data/function_{functionNo}/initial_outputs.npy')

    submissions, results = collatePreviousSubmissions(functionNo)

    combined_Inputs = np.vstack((initialInputs, submissions))
    combined_Outputs = np.concatenate((initialOutputs, results))

    assert combined_Inputs.shape[1] == initialInputs.shape[1]
    assert combined_Outputs.shape[0] == combined_Inputs.shape[0]

    return combined_Inputs, combined_Outputs


In [8]:
f1_Inputs, f1_Outputs = combineInitialDataAndSubmissionsToDate(1)
findNextGuess('F1', f1_Inputs, f1_Outputs)

********************
F1  -  2 D
********************
 Inputs -   Min: [0.029245 0.037348] , Max:  [0.88388983 0.8798981 ]
 Output -   Min: -0.0036060626443634764 , Max (Best):  2.6752879910742468e-09

[[ 5.000000e-001  5.000000e-001  2.675288e-009]
 [ 7.310236e-001  7.329999e-001  7.710875e-016]
 [ 6.834182e-001  8.610575e-001  2.535001e-040]
 [ 5.743292e-001  8.798981e-001  1.033078e-046]
 [ 8.838898e-001  5.822540e-001  6.229856e-048]
 [ 3.194039e-001  7.629594e-001  1.322677e-079]
 [ 8.250725e-002  4.034875e-001  3.606771e-081]
 [ 8.403534e-001  2.647316e-001  3.341771e-124]
 [ 3.050000e-002  3.734800e-002  1.733985e-209]
 [ 2.924500e-002  7.675600e-002 -1.187622e-190]
 [ 3.126912e-001  7.872278e-002 -2.089093e-091]
 [ 4.104371e-001  1.475543e-001 -2.159249e-054]
 [ 4.310290e-001  8.143680e-001 -2.995340e-053]
 [ 6.501141e-001  6.815264e-001 -3.606063e-003]]

Starting 2D Bayes Optimisation from 14 known samples

Best GP kernel and hyperparams for problem is ${'alpha': 1e-08, 'kernel

In [9]:
f2_Inputs, f2_Outputs = combineInitialDataAndSubmissionsToDate(2)
findNextGuess('F2', f2_Inputs, f2_Outputs)

********************
F2  -  2 D
********************
 Inputs -   Min: [0.14269907 0.02869772] , Max:  [0.87779099 0.970764  ]
 Output -   Min: -0.06562362443733738 , Max (Best):  0.6112052157614438

[[ 0.702637  0.926564  0.611205]
 [ 0.665800  0.123969  0.538996]
 [ 0.877791  0.778628  0.420586]
 [ 0.845275  0.711120  0.293993]
 [ 0.750921  0.829565  0.259756]
 [ 0.438166  0.685018  0.244619]
 [ 0.454647  0.290455  0.214965]
 [ 0.600000  0.500000  0.144121]
 [ 0.778688  0.970764  0.093698]
 [ 0.350915  0.117067  0.048338]
 [ 0.341750  0.028698  0.038749]
 [ 0.577713  0.771973  0.023106]
 [ 0.338648  0.213867 -0.013858]
 [ 0.142699  0.349005 -0.065624]]

Starting 2D Bayes Optimisation from 14 known samples

Best GP kernel and hyperparams for problem is ${'alpha': 0.0001, 'kernel': RBF(length_scale=1), 'n_restarts_optimizer': 5}
Using Expected Improvement Acquisition function with xi = 0
	32768 Sobol candidates, best 64 to be minimised in local search
	Initial acquisition function stats

In [10]:
f3_Inputs, f3_Outputs = combineInitialDataAndSubmissionsToDate(3)
findNextGuess('F3', f3_Inputs, f3_Outputs)

********************
F3  -  3 D
********************
 Inputs -   Min: [0.04680895 0.028783   0.06608864] , Max:  [0.96599485 0.94135983 0.99088187]
 Output -   Min: -0.3989255131463011 , Max (Best):  -0.016667499870921285

[[ 0.151837  0.439991  0.990882 -0.398926]
 [ 0.645503  0.397143  0.919771 -0.113869]
 [ 0.431029  0.814368  0.806413 -0.098068]
 [ 0.431029  0.814368  0.806413 -0.070739]
 [ 0.046809  0.231360  0.770618 -0.118048]
 [ 0.134015  0.028783  0.755137 -0.187030]
 [ 0.965995  0.861120  0.566829 -0.056758]
 [ 0.371452  0.413066  0.461483 -0.016667]
 [ 0.134622  0.219917  0.458206 -0.048008]
 [ 0.220549  0.297825  0.343555 -0.046947]
 [ 0.492581  0.611593  0.340176 -0.034835]
 [ 0.242114  0.644074  0.272433 -0.087963]
 [ 0.345523  0.941360  0.269363 -0.110621]
 [ 0.171525  0.343917  0.248737 -0.112122]
 [ 0.666014  0.671985  0.246295 -0.105965]
 [ 0.746912  0.284196  0.226300 -0.131461]
 [ 0.534906  0.398501  0.173389 -0.111415]
 [ 0.170477  0.697032  0.149169 -0.094190]
 [ 

In [11]:
f4_Inputs, f4_Outputs = combineInitialDataAndSubmissionsToDate(4)
findNextGuess('F4', f4_Inputs, f4_Outputs)

********************
F4  -  4 D
********************
 Inputs -   Min: [0.006332   0.0062504  0.04218635 0.08151656] , Max:  [0.98562189 0.91959232 0.99586    0.99948256]
 Output -   Min: -34.63184372743062 , Max (Best):  0.5348195285562913

[[ 6.332000e-03  1.463550e-01  9.958600e-01  9.348320e-01 -3.463184e+01]
 [ 4.885942e-01  2.119651e-01  9.391779e-01  3.761917e-01 -1.781800e+01]
 [ 4.006650e-01  7.257425e-02  8.867683e-01  2.438423e-01 -1.704923e+01]
 [ 9.483894e-01  8.945130e-01  8.516378e-01  5.521963e-01 -3.262566e+01]
 [ 9.571353e-01  5.976444e-01  7.661139e-01  7.762099e-01 -2.731640e+01]
 [ 3.469621e-01  6.250400e-03  7.605636e-01  6.130236e-01 -1.605377e+01]
 [ 3.874878e-01  8.045323e-01  7.517955e-01  7.238274e-01 -1.944156e+01]
 [ 8.548108e-01  4.939646e-01  7.353100e-01  8.080920e-01 -2.313943e+01]
 [ 7.386130e-01  4.821026e-01  7.093664e-01  5.039700e-01 -1.312278e+01]
 [ 8.013027e-01  5.002311e-01  7.066446e-01  1.951028e-01 -1.548708e+01]
 [ 6.551155e-01  7.239183e-02

In [12]:
f5_Inputs, f5_Outputs = combineInitialDataAndSubmissionsToDate(5)
findNextGuess('F5', f5_Inputs, f5_Outputs)

********************
F5  -  4 D
********************
 Inputs -   Min: [0.013737   0.03819337 0.08894684 0.07288048] , Max:  [0.924901   0.86254031 1.         0.9576439 ]
 Output -   Min: 0.1129397953712203 , Max (Best):  2263.948440073915

[[3.251100e-01 8.389740e-01 1.000000e+00 9.341090e-01 2.263948e+03]
 [2.983980e-01 8.408080e-01 9.794320e-01 9.188810e-01 1.959096e+03]
 [2.241890e-01 8.464805e-01 8.794842e-01 8.785157e-01 1.088860e+03]
 [6.834322e-01 1.186626e-01 8.290459e-01 5.675766e-01 7.843439e+01]
 [1.268847e-01 1.534296e-01 7.701622e-01 1.905181e-01 9.972332e+00]
 [5.111418e-01 8.179570e-01 7.287104e-01 1.123536e-01 7.972913e+01]
 [8.364780e-01 1.936096e-01 6.638927e-01 7.856489e-01 2.583705e+02]
 [7.586529e-01 5.365177e-01 6.560004e-01 3.603416e-01 1.830138e+01]
 [1.198792e-01 8.625403e-01 6.433313e-01 8.498038e-01 4.316128e+02]
 [3.068887e-01 3.168781e-01 6.226345e-01 9.539906e-02 6.347672e+01]
 [1.914471e-01 3.819337e-02 6.074178e-01 4.145841e-01 6.444344e+01]
 [6.774911e-

In [13]:
f6_Inputs, f6_Outputs = combineInitialDataAndSubmissionsToDate(6)
findNextGuess('F6', f6_Inputs, f6_Outputs)


********************
F6  -  5 D
********************
 Inputs -   Min: [0.021081  0.076503  0.0165229 0.042143  0.003667 ] , Max:  [0.95773967 0.93187122 0.989507   0.96165559 0.89281919]
 Output -   Min: -2.5711696316081234 , Max (Best):  -0.2776577094327388

[[ 0.585939  0.538496  0.989507  0.863517  0.003667 -0.897936]
 [ 0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343]
 [ 0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786]
 [ 0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682]
 [ 0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839]
 [ 0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265]
 [ 0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049]
 [ 0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200]
 [ 0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558]
 [ 0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955]
 [ 0.400740  0.365117  0.465329  0.765461  0.143118 -0.277658]
 [ 0.782880  0.536336  0.443284  0.859700  0.01

In [14]:
f7_Inputs, f7_Outputs = combineInitialDataAndSubmissionsToDate(7)
findNextGuess('F7', f7_Inputs, f7_Outputs)

********************
F7  -  6 D
********************
 Inputs -   Min: [0.011684   0.01181284 0.00363456 0.001006   0.01494418 0.05109986] , Max:  [0.94245084 0.932801   0.92457051 0.96101714 0.9986547  0.95101392]
 Output -   Min: 0.0027014650245082332 , Max (Best):  1.627092775388822

[[7.262857e-01 4.648958e-01 9.245705e-01 8.072454e-01 6.354384e-01
  1.434179e-01 6.676325e-02]
 [1.188670e-01 6.150549e-01 9.058164e-01 8.553003e-01 4.136314e-01
  5.852356e-01 6.142430e-02]
 [2.726238e-01 3.244954e-01 8.971088e-01 8.329512e-01 1.540627e-01
  7.958636e-01 6.044327e-01]
 [2.263479e-01 1.150258e-01 8.247497e-01 9.453837e-01 9.053115e-01
  9.510139e-01 7.016028e-03]
 [6.661051e-02 5.280451e-01 8.160952e-01 9.610171e-01 8.650933e-02
  7.777882e-01 5.164572e-01]
 [1.486470e-01 3.394336e-02 7.288056e-01 3.160665e-01 2.176938e-02
  5.169178e-01 6.115255e-01]
 [8.062821e-01 3.241224e-01 7.260760e-01 1.487121e-01 7.193764e-01
  3.628840e-01 2.134252e-02]
 [6.302176e-01 8.380969e-01 6.800131e-01 

In [15]:
f8_Inputs, f8_Outputs = combineInitialDataAndSubmissionsToDate(8)
findNextGuess('F8', f8_Inputs, f8_Outputs)

********************
F8  -  8 D
********************
 Inputs -   Min: [0.00907698 0.002882   0.02292868 0.         0.00964888 0.02211341
 0.03590888 0.02729   ] , Max:  [0.98594539 0.97397979 0.9988855  0.958365   0.989136   0.993478
 0.99291449 0.9887551 ]
 Output -   Min: 5.5921933895401965 , Max (Best):  9.838102201175

[[9.849332e-01 6.995063e-01 9.988855e-01 1.801485e-01 5.801431e-01
  2.310872e-01 4.908269e-01 3.136827e-01 5.592193e+00]
 [1.780070e-01 5.662227e-01 9.948618e-01 2.103250e-01 3.201527e-01
  7.079088e-01 6.353845e-01 1.071316e-01 7.005227e+00]
 [1.761500e-01 2.939614e-01 9.756800e-01 7.939363e-01 9.234008e-01
  3.084229e-02 8.032545e-01 5.958976e-01 6.451943e+00]
 [3.515119e-01 5.900649e-01 9.094363e-01 6.784084e-01 2.128257e-01
  8.846038e-02 4.101530e-01 1.957243e-01 7.131624e+00]
 [6.049945e-01 2.922150e-01 9.084527e-01 3.555062e-01 2.016687e-01
  5.753380e-01 3.103110e-01 7.342814e-01 7.398721e+00]
 [8.988871e-01 5.236417e-01 8.767833e-01 2.186964e-01 9.002609e-0

In [16]:
formatted_data = {}

print(f'0 - Xi {XI_EXPLOIT} exploit')
print(f'1 - Xi {XI_SMALL} small explore')
print(f'2 - Xi {XI_MODERATE }medium explore')
print(f'3 - Xi {XI_HIGH} higher Explore')
print(f'4 - UCB k {KAPPA_EXPLOIT} exploit')
print(f'5 - UCB k {KAPPA_BALANCED} balanced')
print(f'6 - UCB k {KAPPA_EXPLORE} medium explore')
print(f'7 - UCB k {KAPPA_EXTREME_EXPLORE} extreme Explore')
print()

for fname, gpKernel in gpKernels.items():
    print(f"{fname}: {gpKernel}")

print()


for fname, values in runResults.items():
    formatted_data[fname] = {}
    for k, v in values.items():
        # Keep the hyphen-separated string as-is
        formatted_data[fname][k] = v

# Optional: print in a readable format
for fname, values in formatted_data.items():
    print(f"\n{fname}:")
    for k, vec_str in values.items():
        print(f"{k}: {vec_str}")

0 - Xi 0 exploit
1 - Xi 0.1 small explore
2 - Xi 0.5medium explore
3 - Xi 20 higher Explore
4 - UCB k 0.1 exploit
5 - UCB k 5 balanced
6 - UCB k 10 medium explore
7 - UCB k 20 extreme Explore

F1: {'alpha': 1e-08, 'kernel': Matern(length_scale=1, nu=0.5), 'n_restarts_optimizer': 5}
F2: {'alpha': 0.0001, 'kernel': RBF(length_scale=1), 'n_restarts_optimizer': 5}
F3: {'alpha': 0.01, 'kernel': Matern(length_scale=1, nu=0.5), 'n_restarts_optimizer': 20}
F4: {'alpha': 1e-08, 'kernel': RationalQuadratic(alpha=1, length_scale=1), 'n_restarts_optimizer': 10}
F5: {'alpha': 0.01, 'kernel': Matern(length_scale=2, nu=0.5), 'n_restarts_optimizer': 20}
F6: {'alpha': 0.01, 'kernel': RationalQuadratic(alpha=1, length_scale=1), 'n_restarts_optimizer': 5}
F7: {'alpha': 0.0001, 'kernel': RationalQuadratic(alpha=1, length_scale=2), 'n_restarts_optimizer': 5}
F8: {'alpha': 0.01, 'kernel': RationalQuadratic(alpha=1, length_scale=1), 'n_restarts_optimizer': 10}


F1:
0: 0.993381-0.994548
1: 0.005040-0.998743
