## Setup

In [60]:
import numpy as np
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
from scipy.stats._qmc import Sobol
from scipy.stats import norm
from scipy.optimize import minimize
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, Matern
from sklearn.model_selection import GridSearchCV

from dataloading_utils import (combineInitialDataAndSubmissionsToDate, sortByLargestOutputDescending)


import warnings
warnings.filterwarnings('ignore')

# A nod to Hitchhikers guide to the Galaxy
random_seed=42
np.random.seed(random_seed)

#UCB -  Kappa
# 0.1-1 Exploitation
# 2-5 Balance
# 5-10 Exploratory
KAPPA_BALANCED = 5
KAPPA_EXPLOIT = 0.1
KAPPA_EXPLORE = 10
KAPPA_EXTREME_EXPLORE = 20

KAPPAS = [KAPPA_EXPLOIT, KAPPA_BALANCED, KAPPA_EXPLORE,KAPPA_EXTREME_EXPLORE]


#EI
#0 - Exploitation
#0.01-0.1 - Small Explore
#0.1-0.5 - Moderate Explore
# 0.5+ - Higher explore
XI_EXPLOIT=0
XI_SMALL = 0.1
XI_MODERATE = 0.5
XI_HIGH=20


XIS = [XI_EXPLOIT,XI_SMALL, XI_MODERATE, XI_HIGH]

ACQUISTION_EI = 'ei'
ACQUISTION_UCB = 'ucb'




In [61]:
def upper_confidence_bound(mu, sigma, kappa):
    """
    Upper Confidence Bound (UCB) acquisition function.
    
    UCB = mean + kappa * std
    
    Parameters:
    -----------
    mu : predicted mean
    sigma : predicted standard deviation
    kappa : exploration parameter (higher = more exploration)
    """
    return mu + kappa * sigma


def expected_improvement(mu, sigma, y_best, xi):
    """
    Expected Improvement (EI) acquisition function.
    
    EI = E[max(f(x) - f(x_best), 0)]
    
    Parameters:
    -----------
    mu : predicted mean
    sigma : predicted standard deviation  
    y_best : best observed value so far
    xi : exploration parameter
    """
    # To avoid division by zero, clamp sigma to a very small non-zero - we also add exit clause later for same value.
    sigma = np.maximum(sigma, 1e-16)

    with np.errstate(divide='warn'):
        improvement = mu - y_best - xi
        Z = improvement / sigma
        ei = improvement * norm.cdf(Z) + sigma * norm.pdf(Z)
        ei[sigma == 1e-16] = 0.0
    return ei


In [62]:

from sklearn.gaussian_process.kernels import WhiteKernel


def fmt(v):
        return float(f"{v:.8f}")


def summary_stats(x):
    return {
        "min": fmt(np.min(x)),
        "max": fmt(np.max(x)),
        "mean": fmt(np.mean(x)),
        "std": fmt(np.std(x)),
        "q1": fmt(np.percentile(x, 25)),
        "median": fmt(np.percentile(x, 50)),
        "q3": fmt(np.percentile(x, 75)),
    }

def findTunedGaussianProcessRegressor(X_samples, y_samples):
    n_dims = X_samples.shape[1]

    base_kernels = [
        ConstantKernel(1.0) * RBF(length_scale=np.ones(n_dims)),
        ConstantKernel(1.0) * Matern(length_scale=np.ones(n_dims), nu=0.5),
        ConstantKernel(1.0) * Matern(length_scale=np.ones(n_dims), nu=1.5),
        ConstantKernel(1.0) * Matern(length_scale=np.ones(n_dims), nu=2.5),
    ]
    kernels = [k + WhiteKernel() for k in base_kernels]

    param_grid = {
        'kernel': kernels,
        'n_restarts_optimizer': [10]
    }

    gp = GaussianProcessRegressor(normalize_y=True)

    grid_search = GridSearchCV(gp, param_grid, cv=5, n_jobs=-1, scoring='neg_mean_squared_error')
    grid_search.fit(X_samples, y_samples)

    return grid_search.best_estimator_, grid_search.best_params_




# def findTunedGaussianProcessRegressor(X_samples, y_samples):
#     n_dims = X_samples.shape[1]
#
#     # ARD kernels (vector length_scale)
#     rbf_ard = RBF(length_scale=np.ones(n_dims),
#                   length_scale_bounds=(1e-2, 1e2))
#     rbf_ardC = RBF(length_scale=np.ones(n_dims),
#                   length_scale_bounds=(1e-2, 1e2)) * ConstantKernel(1.0)
#
#     matern_05 = Matern(length_scale=np.ones(n_dims), nu=0.5,
#                        length_scale_bounds=(1e-2, 1e2))
#     matern_15 = Matern(length_scale=np.ones(n_dims), nu=1.5,
#                        length_scale_bounds=(1e-2, 1e2))
#     matern_25 = Matern(length_scale=np.ones(n_dims), nu=2.5,
#                        length_scale_bounds=(1e-2, 1e2))
#
#     matern_05C = Matern(length_scale=np.ones(n_dims), nu=0.5,
#                        length_scale_bounds=(1e-2, 1e2)) * ConstantKernel(1.0)
#     matern_15C = Matern(length_scale=np.ones(n_dims), nu=1.5,
#                        length_scale_bounds=(1e-2, 1e2)) * ConstantKernel(1.0)
#     matern_25C = Matern(length_scale=np.ones(n_dims), nu=2.5,
#                        length_scale_bounds=(1e-2, 1e2)) * ConstantKernel(1.0)
#
#     param_grid = {
#         'kernel': [
#             rbf_ard,
#             rbf_ardC,
#             matern_05, matern_15, matern_25,
#             matern_05C, matern_15C, matern_25C,
#         ],
#         'alpha': [1e-8, 1e-6, 1e-4, 1e-2],
#         'n_restarts_optimizer': [5, 10, 20]
#     }
#
#     gp = GaussianProcessRegressor(normalize_y=True)
#
#     grid_search = GridSearchCV(gp, param_grid, cv=5, n_jobs=-1, scoring='neg_mean_squared_error')
#     grid_search.fit(X_samples, y_samples)
#
#     return grid_search.best_estimator_, grid_search.best_params_


def penaltyWeightAndScaleForDimension(d):
    #Curse of dimensionality means this needs to be much tighter at higher dimensions
    #This is intended to reduce the acquisition function's information gain by 10% if the point has a Euclidean distance of 1/20th or 1/50th of a boundary.
    if d <= 5:
        return 0.1, 0.05
    else:
        return 0.1, 0.02


def get_length_scale(kernel):
    if hasattr(kernel, "length_scale"):
        return kernel.length_scale
    elif hasattr(kernel, "k1"):
        return get_length_scale(kernel.k1)
    elif hasattr(kernel, "k2"):
        return get_length_scale(kernel.k2)
    return None



def bayesian_optimization_next_point(
        n_dims,
        X_samples,
        y_samples,
        acquisition,
        kappa = KAPPA_BALANCED,
        xi = XI_SMALL,
        n_sobol=None,
        n_local=None,
        gp=None,
        excludeDuplicates = True):

    """
    Bayesian Optimization acquisition optimizer - after research about search spaces.
    Parameters
    ----------
    n_dims : int
        Number of dimensions
    X_samples : array (N, D)
        Existing sample inputs
    y_samples : array (N,)
        Existing sample outputs
    acquisition : str
        'ei' or 'ucb'
    n_sobol : int
        Number of Sobol candidate points
    n_local : int
        Number of local optimizations
    kappa: int
        Exploration parameter (higher = more exploration)
    gp: GaussianProcessor
        Gaussian Processor to use on fitting≥
    """

    if n_sobol is None:
        n_sobol = 16384 * n_dims

    if n_local is None:
        n_local = 32 * n_dims

    bounds = [(0.0, 1.0) for _ in range(n_dims)]
    penaltyWeight, penalityScale = penaltyWeightAndScaleForDimension(n_dims)

    if acquisition == ACQUISTION_EI:
        print(f"Using Expected Improvement Acquisition function with xi = {xi}")
    else:
        print(f"Using UCB Acquisition function with Kappa = {kappa}")


    # -----------------------------
    # 1. Fit Gaussian Process - or assume one has been fitted
    #
    #  alpha is the noise level
    #  n_restarts_optimizer is a hyper-parameter
    #  normalize_y improves stability
    # -----------------------------
    if gp is None:
        kernel = ConstantKernel(1.0) * Matern(nu=2.5)
        gp = GaussianProcessRegressor(
            kernel=kernel,
            alpha=1e-6,
            n_restarts_optimizer=10,
            normalize_y=True
        )
        gp.fit(X_samples, y_samples)
        print(f"Fitted default GaussianProcessRegressor since one not provided")

    # -----------------------------
    # 2. Acquisition function
    # -----------------------------

    # -----------------------------
    # 2.1 Boundary Penalty.
    # GP tends to hug the boundary, so add a penalty if a suggested point is close to boundary.
    # Scale controls how far from the boundary the penalty reaches. At scale=0.05, a point at x=0.05 gets a penalty of exp(-1) ≈ 0.37, meaning the penalty is significant only within the last ~5% of the search space.
    # Weight controls how strongly that penalty suppresses the acquisition value. At weight=0.1, the maximum possible suppression is 10% of the acquisition value.
    #
    # -----------------------------
    def boundary_penalty(X, weight=0.1, scale=0.05):
        X = np.atleast_2d(X)
        d = np.minimum(X, 1.0 - X)    #Find point closest to boundary at 0 or 1 in any dimension.
        penalty = np.mean(np.exp(-d / scale), axis=1)   #exp(-small) tends towards 1, exp(-large) tends towards 0. Mean takes into account other dimensions.
        return weight * penalty


    def acq(X):
        X = np.atleast_2d(X)
        mu, sigma = gp.predict(X, return_std=True)

        if acquisition == ACQUISTION_EI:
            val = expected_improvement(mu, sigma, y_samples.max(), xi)
        else:
            val = upper_confidence_bound(mu, sigma, kappa)

        penalty = boundary_penalty(X, weight=penaltyWeight, scale=penalityScale)
        return val * (1 - penalty)


    # -----------------------------
    # 3. Sobol global search
    #
    # Provides a better search than random of the space, but we then run a vectorized evaluation loop and pick the top results to focus optimizing
    # i.e. maximising in local optimization (actually we minimise the -value)
    # -----------------------------
    sobol = Sobol(d=n_dims, scramble=True, seed=random_seed*n_dims) #Stop the same points for each function.

    X_candidates = sobol.random(n_sobol)
    acq_vals = acq(X_candidates)

    # Filter out duplicate candidates, based on Eucledian distance because acquisition functions can suggest previous points.
    def is_duplicate(x, X_samples, tol=1e-5):
        return np.any(np.linalg.norm(X_samples - x, axis=1) < tol)

    if (excludeDuplicates):
        mask = np.array([not is_duplicate(x, X_samples) for x in X_candidates])
        X_candidates = X_candidates[mask]
        acq_vals = acq_vals[mask]


    # Pick best Sobol points
    best_idx = np.argsort(-acq_vals)[:n_local]
    X_start = X_candidates[best_idx]

    print(f"\t{ len(X_candidates) } Sobol candidates, best { len(X_start) } to be minimised in local search")
    print(f"\tInitial acquisition function stats { summary_stats(acq_vals) }")

    # -----------------------------
    # 4. Local optimization
    # -----------------------------
    def objective(x):
        return -acq(x)  # minimize negative acquisition

    best_x = None
    best_val = -np.inf

    for i, x0 in enumerate(X_start):
        result = minimize(
            objective,
            x0,
            bounds=bounds,
            method="L-BFGS-B"
        )

        val = -result.fun

        if val > best_val:
            best_val = val
            best_x = result.x
            print(f"\tLocal search {i+1}/{n_local}, x={result.x}, val={val}, best={best_val:.10f}")

    return best_x, best_val, X_start



In [63]:
def formatOutputForSubmission( nextInputToTest: ndarray):
    return np.array2string(nextInputToTest, separator='-', precision=6, floatmode='fixed').strip('[]')


def findNextGuess(functionName, f_Inputs, f_Outputs, showKnown=True):

    f_maxInput = np.max(f_Inputs, axis=0) #Output per dimension
    f_minInput = np.min(f_Inputs, axis=0)
    f_maxOutput = np.max(f_Outputs)
    f_minOutput = np.min(f_Outputs)
    numDimensions = len(f_maxInput)

    f_inputOutput = np.column_stack((f_Inputs, f_Outputs))
    f_inputOutputSorted = sortByLargestOutputDescending(f_inputOutput)

    print('********************')
    print(functionName, ' - ', numDimensions, 'D')
    print('********************')
    print(' Inputs -   Min:',  f_minInput, ', Max: ', f_maxInput )
    print(' Output -   Min:',  f_minOutput, ', Max (Best): ', f_maxOutput)

    if (showKnown):
        print()
        print(np.array2string(f_inputOutputSorted, floatmode='fixed', precision=6))
        print()

    print(f"Starting {numDimensions}D Bayes Optimisation from {len(f_Inputs)} known samples")
    print()


    #Solve the GaussianProcessor hyper parameters and record the best fit.
    gpr, bestParams = findTunedGaussianProcessRegressor(f_Inputs, f_Outputs)
    print(f"Best GP kernel and hyperparams for problem initially is ${bestParams}")
    print()

    #Fit GaussianProcesses to samples provided
    gpr.fit(f_Inputs, f_Outputs)
    gpKernels[functionName] = gpr.kernel_   #Get the kernel after it has been fitted.


    lengthScale = get_length_scale(gpr.kernel_)
    if lengthScale is not None:
        print(f"Automatic Relevance Determination (by dimension) from GaussianProcessorRegressor model fit is {lengthScale}")


    functionProposedPoints = {}
    count = -1

    # EI
    for xi in XIS:
        nextInputToTest, acqFunctionValue, acqCandidatePoints  = bayesian_optimization_next_point(
            n_dims=numDimensions,
            X_samples=f_Inputs,
            y_samples=f_Outputs,
            acquisition=ACQUISTION_EI,
            xi=xi,
            gp=gpr
        )

        count += 1
        functionProposedPoints[count] = formatOutputForSubmission(nextInputToTest)
        print()
        print(f'\tProposed next point to try: {functionProposedPoints[count]}')
        print()

    for k in KAPPAS:
        nextInputToTest, acqFunctionValue, acqCandidatePoints  = bayesian_optimization_next_point(
            n_dims=numDimensions,
            X_samples=f_Inputs,
            y_samples=f_Outputs,
            acquisition=ACQUISTION_UCB,
            kappa=k,
            gp=gpr
        )
        count += 1
        functionProposedPoints[count] = formatOutputForSubmission(nextInputToTest)
        print()
        print(f'\tProposed next point to try: {functionProposedPoints[count]}')
        print()

    runResults[functionName] = functionProposedPoints


In [64]:

#Store Results from runs
runResults = {}
gpKernels = {}


In [65]:
f1_Inputs, f1_Outputs = combineInitialDataAndSubmissionsToDate(1)
findNextGuess('F1', f1_Inputs, f1_Outputs)

********************
F1  -  2 D
********************
 Inputs -   Min: [0.00787  0.037348] , Max:  [0.88388983 0.990426  ]
 Output -   Min: -0.0036060626443634764 , Max (Best):  5.350575982148602e-09

[[ 5.500000e-001  5.500000e-001  5.350576e-009]
 [ 5.000000e-001  5.000000e-001  2.675288e-009]
 [ 5.000020e-001  3.340760e-001  2.397010e-010]
 [ 7.310236e-001  7.329999e-001  7.710875e-016]
 [ 6.834182e-001  8.610575e-001  2.535001e-040]
 [ 5.743292e-001  8.798981e-001  1.033078e-046]
 [ 8.838898e-001  5.822540e-001  6.229856e-048]
 [ 3.194039e-001  7.629594e-001  1.322677e-079]
 [ 8.250725e-002  4.034875e-001  3.606771e-081]
 [ 8.403534e-001  2.647316e-001  3.341771e-124]
 [ 3.050000e-002  3.734800e-002  1.733985e-209]
 [ 7.870000e-003  9.904260e-001  0.000000e+000]
 [ 2.924500e-002  7.675600e-002 -1.187622e-190]
 [ 3.126912e-001  7.872278e-002 -2.089093e-091]
 [ 4.104371e-001  1.475543e-001 -2.159249e-054]
 [ 4.310290e-001  8.143680e-001 -2.995340e-053]
 [ 2.386200e-001  4.997890e-001 

In [66]:
f2_Inputs, f2_Outputs = combineInitialDataAndSubmissionsToDate(2)
findNextGuess('F2', f2_Inputs, f2_Outputs)

********************
F2  -  2 D
********************
 Inputs -   Min: [0.         0.02869772] , Max:  [0.996055 0.970764]
 Output -   Min: -0.06562362443733738 , Max (Best):  0.6390022767203885

[[ 0.720000  0.880000  0.639002]
 [ 0.702637  0.926564  0.611205]
 [ 0.665800  0.123969  0.538996]
 [ 0.877791  0.778628  0.420586]
 [ 0.845275  0.711120  0.293993]
 [ 0.750921  0.829565  0.259756]
 [ 0.438166  0.685018  0.244619]
 [ 0.454647  0.290455  0.214965]
 [ 0.600000  0.500000  0.144121]
 [ 0.778688  0.970764  0.093698]
 [ 0.350915  0.117067  0.048338]
 [ 0.341750  0.028698  0.038749]
 [ 0.577713  0.771973  0.023106]
 [ 0.996055  0.236836 -0.006793]
 [ 0.338648  0.213867 -0.013858]
 [ 0.000000  0.500000 -0.031277]
 [ 0.092501  0.897042 -0.043957]
 [ 0.142699  0.349005 -0.065624]]

Starting 2D Bayes Optimisation from 18 known samples

Best GP kernel and hyperparams for problem initially is ${'kernel': 1**2 * Matern(length_scale=[1, 1], nu=1.5) + WhiteKernel(noise_level=1), 'n_restarts_op

In [67]:
f3_Inputs, f3_Outputs = combineInitialDataAndSubmissionsToDate(3)
findNextGuess('F3', f3_Inputs, f3_Outputs)

********************
F3  -  3 D
********************
 Inputs -   Min: [0.04680895 0.028783   0.        ] , Max:  [0.96599485 0.94135983 0.99088187]
 Output -   Min: -0.3989255131463011 , Max (Best):  -0.016667499870921285

[[ 0.371452  0.413066  0.461483 -0.016667]
 [ 0.380000  0.450000  0.400000 -0.022475]
 [ 0.492581  0.611593  0.340176 -0.034835]
 [ 0.600097  0.725136  0.066089 -0.036378]
 [ 0.220549  0.297825  0.343555 -0.046947]
 [ 0.134622  0.219917  0.458206 -0.048008]
 [ 0.965995  0.861120  0.566829 -0.056758]
 [ 0.431029  0.814368  0.806413 -0.070739]
 [ 0.242114  0.644074  0.272433 -0.087963]
 [ 0.500003  0.500001  0.656244 -0.092565]
 [ 0.170477  0.697032  0.149169 -0.094190]
 [ 0.431029  0.814368  0.806413 -0.098068]
 [ 0.666014  0.671985  0.246295 -0.105965]
 [ 0.500001  0.500000  0.000000 -0.107063]
 [ 0.345523  0.941360  0.269363 -0.110621]
 [ 0.534906  0.398501  0.173389 -0.111415]
 [ 0.171525  0.343917  0.248737 -0.112122]
 [ 0.645503  0.397143  0.919771 -0.113869]
 [ 

In [68]:
f4_Inputs, f4_Outputs = combineInitialDataAndSubmissionsToDate(4)
findNextGuess('F4', f4_Inputs, f4_Outputs)

********************
F4  -  4 D
********************
 Inputs -   Min: [0.006332   0.0062504  0.04218635 0.009412  ] , Max:  [0.98562189 0.974595   0.99586    0.99948256]
 Output -   Min: -38.3424877737288 , Max (Best):  0.5781245847042062

[[ 4.300000e-01  4.150000e-01  3.950000e-01  4.200000e-01  5.781246e-01]
 [ 4.315800e-01  4.116090e-01  3.797880e-01  4.129810e-01  5.348195e-01]
 [ 3.670510e-01  3.886210e-01  4.055160e-01  4.587970e-01 -5.269040e-01]
 [ 4.300140e-01  4.541360e-01  4.622970e-01  3.515750e-01 -6.329462e-01]
 [ 4.179160e-01  3.873800e-01  3.700490e-01  3.069200e-01 -8.522905e-01]
 [ 5.777656e-01  4.287717e-01  4.258259e-01  2.490074e-01 -4.025542e+00]
 [ 3.260758e-01  4.723669e-01  4.531920e-01  1.058873e-01 -6.702089e+00]
 [ 2.821384e-01  5.059869e-01  5.305308e-01  9.630162e-02 -7.966775e+00]
 [ 1.248712e-01  1.297702e-01  3.844005e-01  2.870761e-01 -1.006963e+01]
 [ 1.703473e-01  7.569591e-01  2.765205e-01  5.312315e-01 -1.156574e+01]
 [ 2.509462e-01  3.369313e-02 

In [69]:
f5_Inputs, f5_Outputs = combineInitialDataAndSubmissionsToDate(5)
findNextGuess('F5', f5_Inputs, f5_Outputs)

********************
F5  -  4 D
********************
 Inputs -   Min: [0.013737   0.03819337 0.08894684 0.07288048] , Max:  [0.924901 1.       1.       1.      ]
 Output -   Min: 0.1129397953712203 , Max (Best):  4678.3425

[[5.000000e-01 1.000000e+00 1.000000e+00 1.000000e+00 4.678342e+03]
 [4.500000e-01 1.000000e+00 1.000000e+00 1.000000e+00 4.598116e+03]
 [3.251100e-01 8.389740e-01 1.000000e+00 9.341090e-01 2.263948e+03]
 [3.251100e-01 8.389740e-01 1.000000e+00 9.341090e-01 2.263948e+03]
 [2.983980e-01 8.408080e-01 9.794320e-01 9.188810e-01 1.959096e+03]
 [5.792990e-01 2.734650e-01 9.003050e-01 1.000000e+00 1.193843e+03]
 [2.241890e-01 8.464805e-01 8.794842e-01 8.785157e-01 1.088860e+03]
 [1.198792e-01 8.625403e-01 6.433313e-01 8.498038e-01 4.316128e+02]
 [4.389334e-01 7.740918e-01 3.781671e-01 9.336962e-01 3.558068e+02]
 [8.364780e-01 1.936096e-01 6.638927e-01 7.856489e-01 2.583705e+02]
 [4.634423e-01 6.300245e-01 1.079065e-01 9.576439e-01 2.332236e+02]
 [3.523563e-01 3.222415e-01 

In [70]:
f6_Inputs, f6_Outputs = combineInitialDataAndSubmissionsToDate(6)
findNextGuess('F6', f6_Inputs, f6_Outputs)


********************
F6  -  5 D
********************
 Inputs -   Min: [0.0088    0.076503  0.0165229 0.014517  0.003667 ] , Max:  [0.95773967 0.93187122 0.989507   0.992791   0.991413  ]
 Output -   Min: -2.5711696316081234 , Max (Best):  -0.2776577094327388

[[ 0.400740  0.365117  0.465329  0.765461  0.143118 -0.277658]
 [ 0.500000  0.250000  0.450000  0.920000  0.050000 -0.589917]
 [ 0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265]
 [ 0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237]
 [ 0.585939  0.538496  0.989507  0.863517  0.003667 -0.897936]
 [ 0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757]
 [ 0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785]
 [ 0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955]
 [ 0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786]
 [ 0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049]
 [ 0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247]
 [ 0.757594  0.355831  0.016523  0.434207  0.11

In [71]:
f7_Inputs, f7_Outputs = combineInitialDataAndSubmissionsToDate(7)
findNextGuess('F7', f7_Inputs, f7_Outputs)

********************
F7  -  6 D
********************
 Inputs -   Min: [0.011684   0.01181284 0.00363456 0.001006   0.01494418 0.05109986] , Max:  [0.94245084 0.932801   0.982137   0.96101714 0.9986547  0.984228  ]
 Output -   Min: 0.0027014650245082332 , Max (Best):  1.627092775388822

[[3.161700e-02 4.443610e-01 2.799560e-01 1.730890e-01 3.666070e-01
  7.319880e-01 1.627093e+00]
 [2.000000e-02 4.700000e-01 2.650000e-01 1.950000e-01 3.950000e-01
  7.320000e-01 1.459762e+00]
 [5.789554e-02 4.916722e-01 2.474222e-01 2.181184e-01 4.204283e-01
  7.309698e-01 1.364968e+00]
 [8.816467e-01 2.044502e-01 4.144744e-01 4.203847e-01 2.649150e-01
  7.306602e-01 6.751416e-01]
 [8.786900e-02 1.063190e-01 9.162330e-01 5.129700e-02 3.650500e-01
  9.842280e-01 6.397486e-01]
 [1.486470e-01 3.394336e-02 7.288056e-01 3.160665e-01 2.176938e-02
  5.169178e-01 6.115255e-01]
 [2.726238e-01 3.244954e-01 8.971088e-01 8.329512e-01 1.540627e-01
  7.958636e-01 6.044327e-01]
 [5.430026e-01 9.246939e-01 3.415675e-01 

In [72]:
f8_Inputs, f8_Outputs = combineInitialDataAndSubmissionsToDate(8)
findNextGuess('F8', f8_Inputs, f8_Outputs)

********************
F8  -  8 D
********************
 Inputs -   Min: [0.00907698 0.002882   0.003793   0.         0.00964888 0.02211341
 0.020978   0.02729   ] , Max:  [0.98594539 0.976249   0.9988855  0.970248   0.989136   0.993478
 0.99291449 0.9887551 ]
 Output -   Min: 5.5921933895401965 , Max (Best):  9.94585

[[8.000000e-02 1.000000e-01 5.000000e-02 2.000000e-02 7.000000e-01
  5.500000e-01 1.500000e-01 7.500000e-01 9.945850e+00]
 [1.199190e-01 1.575910e-01 7.379700e-02 0.000000e+00 9.460320e-01
  2.338210e-01 4.595400e-02 5.690100e-01 9.838102e+00]
 [5.644741e-02 6.595555e-02 2.292868e-02 3.878647e-02 4.039354e-01
  8.010553e-01 4.883070e-01 8.930850e-01 9.598482e+00]
 [1.926399e-01 6.306773e-01 4.167958e-01 4.905293e-01 7.960860e-01
  6.545671e-01 2.762412e-01 2.955176e-01 9.344274e+00]
 [4.812453e-01 1.024607e-01 2.194859e-01 6.773224e-01 2.475092e-01
  2.443409e-01 1.638245e-01 7.159616e-01 9.183005e+00]
 [1.451203e-01 1.193275e-01 4.208882e-01 3.876086e-01 1.554228e-01
  8.7

In [73]:
formatted_data = {}

print(f'0 - Xi {XI_EXPLOIT} exploit')
print(f'1 - Xi {XI_SMALL} small explore')
print(f'2 - Xi {XI_MODERATE }medium explore')
print(f'3 - Xi {XI_HIGH} higher Explore')
print(f'4 - UCB k {KAPPA_EXPLOIT} exploit')
print(f'5 - UCB k {KAPPA_BALANCED} balanced')
print(f'6 - UCB k {KAPPA_EXPLORE} medium explore')
print(f'7 - UCB k {KAPPA_EXTREME_EXPLORE} extreme Explore')
print()

for fname, gpKernel in gpKernels.items():
    print(f"{fname}: {gpKernel}")

print()


for fname, values in runResults.items():
    formatted_data[fname] = {}
    for k, v in values.items():
        # Keep the hyphen-separated string as-is
        formatted_data[fname][k] = v

# Optional: print in a readable format
for fname, values in formatted_data.items():
    print(f"\n{fname}:")
    for k, vec_str in values.items():
        print(f"{k}: {vec_str}")

0 - Xi 0 exploit
1 - Xi 0.1 small explore
2 - Xi 0.5medium explore
3 - Xi 20 higher Explore
4 - UCB k 0.1 exploit
5 - UCB k 5 balanced
6 - UCB k 10 medium explore
7 - UCB k 20 extreme Explore

F1: 1.04**2 * Matern(length_scale=[0.0244, 1e+05], nu=0.5) + WhiteKernel(noise_level=1e-05)
F2: 0.955**2 * Matern(length_scale=[0.0608, 1e+05], nu=1.5) + WhiteKernel(noise_level=0.0149)
F3: 1.25**2 * Matern(length_scale=[1.36e+04, 1e+05, 0.0763], nu=2.5) + WhiteKernel(noise_level=0.0488)
F4: 3.16**2 * Matern(length_scale=[1.67, 1.78, 1.79, 1.66], nu=2.5) + WhiteKernel(noise_level=0.000689)
F5: 3.71**2 * Matern(length_scale=[6.42, 1.48, 1.72, 1.04], nu=2.5) + WhiteKernel(noise_level=1e-05)
F6: 2.34**2 * Matern(length_scale=[1.43, 3.2, 2.48, 2.12, 3.43], nu=1.5) + WhiteKernel(noise_level=0.0558)
F7: 0.849**2 * Matern(length_scale=[1.68, 1.38e+04, 1.24e+04, 0.718, 0.33, 0.397], nu=0.5) + WhiteKernel(noise_level=1e-05)
F8: 19.2**2 * Matern(length_scale=[8.85, 12.4, 7.11, 12.6, 20.2, 11.9, 8.92, 1e+05